//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorAppointmentsTBL
    {
        public int id { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual DoctorTBL DoctorTBL { get; set; }
    }
}
