//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorTBL()
        {
            this.MedicalFileDetalisTBLs = new HashSet<MedicalFileDetalisTBL>();
            this.BookingTBLs = new HashSet<BookingTBL>();
            this.DoctorAppointmentsTBLs = new HashSet<DoctorAppointmentsTBL>();
        }
    
        public int Doctorid { get; set; }
        public string DoctorName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Cityid { get; set; }
        public Nullable<int> Areaid { get; set; }
        public Nullable<int> Specialtyid { get; set; }
    
        public virtual AreaTBL AreaTBL { get; set; }
        public virtual CityTBL CityTBL { get; set; }
        public virtual SpecialtyTBL SpecialtyTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalFileDetalisTBL> MedicalFileDetalisTBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTBL> BookingTBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorAppointmentsTBL> DoctorAppointmentsTBLs { get; set; }
    }
}
