//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalFileTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalFileTBL()
        {
            this.MedicalFileDetalisTBLs = new HashSet<MedicalFileDetalisTBL>();
        }
    
        public int id { get; set; }
        public string FileSerial { get; set; }
        public string Discraption { get; set; }
        public Nullable<int> patientid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalFileDetalisTBL> MedicalFileDetalisTBLs { get; set; }
        public virtual PatientTBL PatientTBL { get; set; }
    }
}
