//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalFilesMedicinTBL
    {
        public int id { get; set; }
        public Nullable<int> fileDetaliesID { get; set; }
        public Nullable<int> medicalID { get; set; }
    
        public virtual MedicalFileDetalisTBL MedicalFileDetalisTBL { get; set; }
        public virtual MedicalTBL MedicalTBL { get; set; }
    }
}
