//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientTBL()
        {
            this.BookingTBLs = new HashSet<BookingTBL>();
            this.MedicalFileTBLs = new HashSet<MedicalFileTBL>();
        }
    
        public int PatientId { get; set; }
        public string SerialPatient { get; set; }
        public string PatientName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<int> Areaid { get; set; }
        public Nullable<short> Gender { get; set; }
    
        public virtual AreaTBL AreaTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTBL> BookingTBLs { get; set; }
        public virtual CityTBL CityTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalFileTBL> MedicalFileTBLs { get; set; }
    }
}
